###########################################################################
# Copyright 2019 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# imitations under the License.
###########################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: kappnav.actions.pod
  namespace: {{ .Release.Namespace }}
data:
  url-actions: |
    [
      { 
        "name":"detail", 
        "text":"View detail", 
        "text.nls":"action.url.pod.detail.text",
        "description":"View Pod detail",  
        "description.nls":"action.url.pod.detail.desc", 
{{ if eq .Values.env.kubeEnv "minikube" }}
        "url-pattern":"${builtin.icp-console-url}/pod/${resource.$.metadata.namespace}/${resource.$.metadata.name}?namespace=${resource.$.metadata.namespace}", 
{{ else }}
        "url-pattern":"${builtin.icp-console-url}/workloads/deployments/${resource.$.metadata.namespace}/${snippet.get_name(${func.kubectlGet(deployments, -l, app=${resource.$.metadata.labels.app}, -n, ${resource.$.metadata.namespace}, -o, json)})}/pods/${resource.$.metadata.name}", 
{{ end }}
        "open-window": "current", 
        "menu-item": "false" 
      }
    ]
  snippets: |
    {
      "get_name": "function getName(json) 
                   { 
                     return JSON.parse(json).items[0].metadata.name;
                   }"
    }
